# Generated by Django 4.2 on 2024-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_sitebanner_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس بنر')),
                ('video', models.FileField(upload_to='videos/banners', verbose_name='ویدیو بنر')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
                ('position', models.CharField(choices=[('station_list', 'لیست ایستگاهها'), ('station_detail', 'جزئیات ایستگاه'), ('about_us', 'درباره ما'), ('article_list', 'مقالات'), ('article_detail', 'جزئیات مقاله')], max_length=200, verbose_name='جایگاه نمایشی')),
            ],
            options={
                'verbose_name': 'فیلم تبلیغاتی',
                'verbose_name_plural': 'فیلم های تبلیغاتی',
            },
        ),
    ]
