# Generated by Django 4.2 on 2024-04-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitevideobanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteVideoBanner',
        ),
    ]
