# Generated by Django 4.2 on 2024-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_delete_sitevideobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/banners', verbose_name='ویدیو بنر'),
        ),
    ]
