# Generated by Django 4.2 on 2024-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_sitebanner_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebanner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس تصویر اسلاید'),
        ),
    ]
