# Generated by Django 4.2 on 2025-02-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_remove_sitebanner_image_url_slider_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('station_list', 'لیست ایستگاهها'), ('station_detail', 'جزئیات ایستگاه'), ('about_us', 'درباره ما'), ('article_list', 'مقالات'), ('article_detail', 'جزئیات مقاله'), ('rainfall-24h', 'بارش 24 ساعته و اخیر')], max_length=200, verbose_name='جایگاه نمایشی'),
        ),
    ]
