# Generated by Django 4.2.6 on 2024-01-04 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام')),
                ('code', models.IntegerField(verbose_name='کد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stations', verbose_name='تصویر ایستگاه')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'ایستگاه',
                'verbose_name_plural': 'ایستگاه ها',
            },
        ),
        migrations.CreateModel(
            name='StationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نوع')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'انواع',
            },
        ),
        migrations.CreateModel(
            name='StationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='آی پی کاربر')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_module.station', verbose_name='ایستگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید ایستگاه',
                'verbose_name_plural': 'بازدید های ایستگاه',
            },
        ),
        migrations.CreateModel(
            name='StationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_tags', to='station_module.station')),
            ],
            options={
                'verbose_name': 'تگ ایستگاه',
                'verbose_name_plural': 'تگ های ایستگاه',
            },
        ),
        migrations.CreateModel(
            name='StationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/station-gallery', verbose_name='تصویر')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_module.station', verbose_name='ایستگاه')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='category',
            field=models.ManyToManyField(related_name='station_categories', to='station_module.stationcategory', verbose_name='دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='station',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_module.stationtype', verbose_name='نوع'),
        ),
    ]
