# Generated by Django 4.2.6 on 2024-01-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام')),
                ('code', models.IntegerField(verbose_name='کد')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('category', models.ManyToManyField(related_name='rain_categories', to='station_module.stationcategory', verbose_name='دسته بندی ها')),
                ('parent_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_module.station', verbose_name='ایستگاه والد')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_module.stationtype', verbose_name='نوع')),
            ],
        ),
    ]
