# Generated by Django 4.2.6 on 2024-01-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0002_raingauge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raingauge',
            name='category',
        ),
        migrations.AddField(
            model_name='raingauge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_module.stationcategory', verbose_name='دسته بندی ها'),
        ),
    ]
