# Generated by Django 4.2.6 on 2024-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0003_remove_raingauge_category_raingauge_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raingauge',
            options={'verbose_name': 'بارانسنجی', 'verbose_name_plural': 'بارانسنجی ها'},
        ),
        migrations.AddField(
            model_name='raingauge',
            name='recent_rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='بارندگی اخیر'),
        ),
        migrations.AddField(
            model_name='raingauge',
            name='year_rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='بارندگی سال'),
        ),
    ]
