# Generated by Django 4.2.6 on 2024-01-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0004_alter_raingauge_options_raingauge_recent_rainfall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='recent_rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='بارندگی اخیر'),
        ),
        migrations.AddField(
            model_name='station',
            name='year_rainfall',
            field=models.FloatField(blank=True, null=True, verbose_name='بارندگی سال'),
        ),
    ]
