# Generated by Django 4.2.6 on 2024-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0005_station_recent_rainfall_station_year_rainfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='raingauge',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='شهرستان'),
        ),
    ]
