# Generated by Django 4.2.6 on 2024-01-18 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0006_raingauge_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raingauge',
            name='recent_rainfall',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بارندگی اخیر'),
        ),
        migrations.AlterField(
            model_name='station',
            name='recent_rainfall',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بارندگی اخیر'),
        ),
    ]
