# Generated by Django 5.0.1 on 2024-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0007_alter_raingauge_recent_rainfall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raingauge',
            name='last_rainfall_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت بارندگی اخیر'),
        ),
    ]
