# Generated by Django 5.0.1 on 2024-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0009_alter_raingauge_last_rainfall_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raingauge',
            name='last_rainfall_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت بارندگی اخیر'),
        ),
    ]
