# Generated by Django 5.0.1 on 2024-01-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0012_station_parent_station_alter_station_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='parent_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station_module.station', verbose_name='ایستگاه والد'),
        ),
    ]
