# Generated by Django 5.0.1 on 2024-01-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0013_alter_station_parent_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='parent_station',
        ),
        migrations.AddField(
            model_name='station',
            name='parentt_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station_module.station', verbose_name='ایستگاه والد'),
        ),
    ]
