# Generated by Django 5.0.1 on 2024-01-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0014_remove_station_parent_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='parentt_station',
            new_name='parentstation',
        ),
    ]
