# Generated by Django 5.0.1 on 2024-01-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0015_rename_parentt_station_station_parentstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='parentstation',
        ),
    ]
