# Generated by Django 5.0.1 on 2024-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0017_station_parent_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='شهرستان'),
        ),
        migrations.AddField(
            model_name='station',
            name='last_rainfall_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت بارندگی اخیر'),
        ),
    ]
