# Generated by Django 5.0.1 on 2024-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0018_station_city_station_last_rainfall_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AlterField(
            model_name='station',
            name='short_description',
            field=models.CharField(blank=True, db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
