# Generated by Django 5.0.1 on 2024-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0019_alter_station_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RainGauge',
        ),
    ]
