# Generated by Django 5.0.1 on 2024-02-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0020_delete_raingauge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='کد'),
        ),
    ]
