# Generated by Django 4.2 on 2024-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0021_alter_station_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='کد'),
        ),
    ]


