# Generated by Django 4.2 on 2024-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0022_alter_station_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ارتفاع'),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
