# Generated by Django 4.2 on 2024-04-16 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0023_station_height_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='height',
        ),
        migrations.AddField(
            model_name='station',
            name='elevation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='ارتفاع'),
        ),
    ]
