# Generated by Django 4.2 on 2024-11-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0025_station_rainfall_3h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='rainfall_24h',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بارندگی 24 ساعت اخیر'),
        ),
    ]
