# Generated by Django 4.2 on 2024-12-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0026_station_rainfall_24h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_rainfall_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت بارندگی اخیر'),
        ),
    ]
