# Generated by Django 4.2 on 2024-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0027_alter_station_last_rainfall_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_rainfall_date_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ثبت بارندگی اخیر'),
        ),
    ]
