# Generated by Django 4.2 on 2024-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0029_alter_station_last_rainfall_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='max_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای بیشینه'),
        ),
        migrations.AddField(
            model_name='station',
            name='min_soil_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای کمینه خاک'),
        ),
        migrations.AddField(
            model_name='station',
            name='min_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای کمینه'),
        ),
    ]
