# Generated by Django 4.2 on 2024-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0030_station_max_temp_station_min_soil_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='max_temp',
        ),
        migrations.RemoveField(
            model_name='station',
            name='min_soil_temp',
        ),
        migrations.RemoveField(
            model_name='station',
            name='min_temp',
        ),
        migrations.AddField(
            model_name='station',
            name='max_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='دمای بیشینه'),
        ),
        migrations.AddField(
            model_name='station',
            name='min_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='دمای کمینه'),
        ),
        migrations.AddField(
            model_name='station',
            name='soil_min_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='دمای کمینه خاک'),
        ),
    ]
