# Generated by Django 4.2 on 2024-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0031_remove_station_max_temp_remove_station_min_soil_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='time_update_temp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ بروزرسانی دما'),
        ),
    ]
