# Generated by Django 4.2 on 2024-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_module', '0032_station_time_update_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='max_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='دمای بیشینه'),
        ),
        migrations.AlterField(
            model_name='station',
            name='min_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='دمای کمینه'),
        ),
        migrations.AlterField(
            model_name='station',
            name='soil_min_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='دمای کمینه خاک'),
        ),
    ]
