# Generated by Django 4.2 on 2024-05-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100, verbose_name='نوع مرخصی')),
                ('leave_days', models.IntegerField(verbose_name='تعداد روز مرخصی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع مرخصی')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان مرخصی')),
                ('attachment', models.FileField(upload_to='attachments/', verbose_name='آپلود فایل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'مرخصی',
                'verbose_name_plural': 'مرخصی\u200cها',
            },
        ),
    ]
