# Generated by Django 4.2 on 2024-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
