# Generated by Django 4.2 on 2024-05-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_leave_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('month', models.CharField(max_length=20, verbose_name='ماه')),
                ('day_shifts', models.IntegerField(verbose_name='تعداد شیفت روز')),
                ('night_shifts', models.IntegerField(verbose_name='تعداد شیفت شب')),
                ('leaves', models.IntegerField(verbose_name='تعداد مرخصی')),
                ('late_reports', models.IntegerField(verbose_name='تعداد تاخیر در گزارش')),
                ('early_reports', models.IntegerField(verbose_name='تعداد تعجیل در گزارش')),
                ('incorrect_reports', models.IntegerField(verbose_name='تعداد اشتباه در گزارش')),
                ('station_collaboration', models.IntegerField(verbose_name='همکاری در امورات ایستگاه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'کارکرد ماهانه',
                'verbose_name_plural': 'کارکردهای ماهانه',
            },
        ),
    ]
