# Generated by Django 4.2 on 2024-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_worklog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_worklog_per_month'),
        ),
    ]
