# Generated by Django 4.2 on 2024-05-26 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_worklog_unique_worklog_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='زمان ثبت'),
        ),
    ]
