# Generated by Django 4.2 on 2024-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_worklog_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('responsible', 'مسئول'), ('non_responsible', 'غیر مسئول')], default='non_responsible', max_length=20, verbose_name='نقش'),
        ),
    ]
