# Generated by Django 4.2 on 2024-06-16 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_alter_user_options_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='day_shifts',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 31 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='تعداد شیفت روز'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='early_reports',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 300 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='تعداد تعجیل در گزارش'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='incorrect_reports',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 300 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='تعداد اشتباه در گزارش'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='late_reports',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 300 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='تعداد تاخیر در گزارش'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='leaves',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 31 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='تعداد مرخصی'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='night_shifts',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 31 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='تعداد شیفت شب'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='station_collaboration',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 5 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی -5 است.'}, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)], verbose_name='همکاری در امورات ایستگاه'),
        ),
    ]
