# Generated by Django 4.2 on 2024-06-22 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_alter_worklog_day_shifts_alter_worklog_early_reports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklog',
            old_name='early_reports',
            new_name='late_early_reports'
        ),
        migrations.RenameField(
            model_name='worklog',
            old_name='late_reports',
            new_name='nill_reports'
        )
    ]
