# Generated by Django 4.2 on 2024-11-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_remove_worklog_early_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='late_early_reports',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 300 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='تعداد تاخیر و تعجیل در گزارش'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='nill_reports',
            field=models.IntegerField(error_messages={'max_value': 'مطمئن شوید این مقدار کوچکتر یا مساوی 300 است.', 'min_value': 'مطمئن شوید این مقدار بزرگتر یا مساوی 0 است.'}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='تعداد عدم مخابره در گزارش'),
        ),
    ]
